function(set_project_warnings target enable_werror)
  if (MSVC)
    target_compile_options(${target} PRIVATE /W4 /permissive-)
    if (enable_werror)
      target_compile_options(${target} PRIVATE /WX)
    endif()
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
    if (enable_werror)
      target_compile_options(${target} PRIVATE -Werror)
    endif()
  endif()
endfunction()
